name       : nuvola-app-google-play-music
version    : 5.15
release    : 2
source     :
    - https://github.com/tiliado/nuvola-app-google-play-music/archive/5.15.tar.gz : 579be729e60ccdaad0d944b1c32213f19af09eee861a7478296b3b139dde7da7
license    : BSD-2-Clause
component  : multimedia.audio
summary    : Google Play Music Integration for Nuvola Player 3.
description: |
    Integration of Google Play Music into your linux desktop via Nuvola Player.
builddeps  :
    - scour
    - librsvg-devel
rundeps    :
    - nuvolaplayer
build      : |
    %make
install    : |
    %make_install DEST="$installdir/usr/share/nuvolaplayer3/web_apps"
